title: "Qalem"
email: qalem45@gmail.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Aladin
paginate: 30
disqus: 'demowebsite'
locale: bs_ba
lang: bs_ba
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-1

# Authors
authors:
  aladin:
    name: Aladin
    display_name: Aladin
    avatar: 'assets/images/sal.png'
    email: aladind@gmail.com
    web: https://www.qalem.net/
    twitter: https://twitter.com/wowthemesnet
    description: "Rezultati mog ličnog shvatanja Qur'ana. Prevod i komentar stranu-po-stranu, shvatanje korena, pojmova i tema iz Qur'ana, metodologija, shvatanje ciljeva, koristi i načina korišćenja Qur'ana."
  merjem:
    name: Merjem
    display_name: Merjem
    avatar: 'assets/images/john.png'
    email: merjem@gmail.com
    web: https://qalem.net/
    twitter: https://twitter.com/
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Social
social:
  instagram: https://www.instagram.com/qalem/
  facebook: https://www.facebook.com/groups/660236640767598
  twitter: https://twitter.com/qalem
  youtube: https://youtube.com/qalem

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives